name: mbean_talabat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  cached_network_image: ^3.3.1
  cached_video_player_plus: ^2.0.0
  camera: ^0.10.5+9
  chewie: ^1.8.1
  cloud_firestore: ^4.17.2
  cupertino_icons: ^ 1.0.6
  file_selector: ^1.0.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.2.0
  flutter_inappwebview: ^6.0.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  local_auth: ^2.2.0
  location: ^6.0.1
  material_dialogs: ^1.1.4
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  salomon_bottom_bar: ^3.3.2
  share: ^2.0.4
  share_plus: ^8.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  shimmer_effect: ^1.0.4
  url_launcher: ^6.2.6
  video_compress_plus: ^1.0.0
  video_player: ^2.8.6
  webview_flutter: ^4.7.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mbean_logo_circale.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
